build_report w/ .._SHIP_TARGET=s3: Fix No such file or directory loading the tarballs (#206)
* run-s3-gather-build: script to gather & build from compose db to compose minio s3

found a bug in build_report during hackathon - gather successfully saves
data to s3, but build can't then find it using the same bucket & ship setings

```
$ minio-mc ls -r local/metricsutilitys3/1864272
...
[2025-08-29 20:28:15 UTC] 1.3KiB STANDARD data/2024/04/01/00000000-0000-0000-0000-000000000000-2024-04-01-000000+0000-2024-04-02-000000+0000-0.tar.gz
...
$ metrics-utility build_report --month=2024-04
Automation Controller modules not found in /awx_devel (AWX_PATH). Using mock and continuing.
[ExtractorS3] ERROR: Extracting 1864272/data/2024/04/01/00000000-0000-0000-0000-000000000000-2024-04-01-000000+0000-2024-04-02-000000+0000-0.tar.gz failed with [Errno 2] No such file or directory: '1864272/data/2024/04/01/00000000-0000-0000-0000-000000000000-2024-04-01-000000+0000-2024-04-02-000000+0000-0.tar.gz'
Traceback (most recent call last):
  File "/home/himdel/metrics/metrics-utility/metrics_utility/automation_controller_billing/extract/extractor_s3.py", line 34, in iter_batches
    yield self.process_tarballs(s3_path, temp_dir)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/himdel/metrics/metrics-utility/metrics_utility/automation_controller_billing/extract/base.py", line 60, in process_tarballs
    _safe_extract(path, temp_dir)
  File "/home/himdel/metrics/metrics-utility/metrics_utility/automation_controller_billing/extract/base.py", line 155, in _safe_extract
    with tarfile.open(tar_path, 'r:*') as tar:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/himdel/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/tarfile.py", line 1835, in open
    return func(name, "r", fileobj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/himdel/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/tarfile.py", line 1903, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/himdel/.local/share/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/gzip.py", line 192, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '1864272/data/2024/04/01/00000000-0000-0000-0000-000000000000-2024-04-01-000000+0000-2024-04-02-000000+0000-0.tar.gz'
...
```

* ExtractorS3: use local_path for tarball extraction, not s3_path

s3_path refers to the file on s3, which process_tarballs can't read
local_path refers to the same file downloaded locally from s3

(comes from #75)

* sql dump: adjust data to generate report for 2025-06-13

must have at least 1 non-0 number in failures/ok/skipped/ignored/rescued so as not to get filtered out by sum_reachable_columns

* clean up unused batch_size

* test full s3 gather + build

including asserts for filenames, skipped collectors, and the since-until gather-build inconsistency

* Issue: AAP-52435